### ISSUE TITLE
User SSO Data Explanation...

### ISSUE THREAD

**Issue by palodequeso** [FastComments/fastcomments-code-examples#1]
Hello, I currently plan on using the fast comments API, and just had to verify a quick question, and couldn't find any other way of reaching out. Does the id passed with the user hash make the user unique, even if the username isn't? That's all, thank you so much!

**Comment by winrid** [comment]
@palodequeso So sorry, it seems we had an issue with our notification settings and missed this.

Currently, username and email must also individually be unique. We'll update the documentation.

I'm not sure if this really needs to be the case from an engineering point of view, but we have those constraints to reduce confusion for readers.

**Comment by winrid** [comment]
@palodequeso By the way, you can usually reach us very quickly via https://fastcomments.com/auth/my-account/edit-details

I'll close this for now.
